config/routes.rb
Rails.application.routes.draw do
  resources :type_foods
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/type_food.rb
class TypeFood < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :ID_typefood, :image_url)
    end
end

app/controllers/type_foods_controller.rb
class TypeFoodsController < ApplicationController
  before_action :set_type_food, only: [:show, :edit, :update, :destroy]

  # GET /type_foods
  # GET /type_foods.json
  def index
    @type_foods = TypeFood.all
  end

  # GET /type_foods/1
  # GET /type_foods/1.json
  def show
  end

  # GET /type_foods/new
  def new
    @type_food = TypeFood.new
  end

  # GET /type_foods/1/edit
  def edit
  end

  # POST /type_foods
  # POST /type_foods.json
  def create
    @type_food = TypeFood.new(type_food_params)

    respond_to do |format|
      if @type_food.save
        format.html { redirect_to @type_food, notice: 'Type food was successfully created.' }
        format.json { render :show, status: :created, location: @type_food }
      else
        format.html { render :new }
        format.json { render json: @type_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_foods/1
  # PATCH/PUT /type_foods/1.json
  def update
    respond_to do |format|
      if @type_food.update(type_food_params)
        format.html { redirect_to @type_food, notice: 'Type food was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_food }
      else
        format.html { render :edit }
        format.json { render json: @type_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_foods/1
  # DELETE /type_foods/1.json
  def destroy
    @type_food.destroy
    respond_to do |format|
      format.html { redirect_to type_foods_url, notice: 'Type food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_food
      @type_food = TypeFood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_food_params
      params.require(:type_food).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/type_foods_helper.rb
module TypeFoodsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :ID_typefood %>
    <%= form.text_field :ID_typefood %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Id typefood</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.ID_typefood %></td>
        <td><%= product.image_url %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Id typefood:</strong>
  <%= @product.ID_typefood %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/type_foods/_form.html.erb
<%= form_with(model: type_food, local: true) do |form| %>
  <% if type_food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_food.errors.count, "error") %> prohibited this type_food from being saved:</h2>

      <ul>
        <% type_food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/type_foods/edit.html.erb
<h1>Editing Type Food</h1>

<%= render 'form', type_food: @type_food %>

<%= link_to 'Show', @type_food %> |
<%= link_to 'Back', type_foods_path %>

app/views/type_foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Type Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @type_foods.each do |type_food| %>
      <tr>
        <td><%= type_food.name %></td>
        <td><%= link_to 'Show', type_food %></td>
        <td><%= link_to 'Edit', edit_type_food_path(type_food) %></td>
        <td><%= link_to 'Destroy', type_food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type Food', new_type_food_path %>

app/views/type_foods/new.html.erb
<h1>New Type Food</h1>

<%= render 'form', type_food: @type_food %>

<%= link_to 'Back', type_foods_path %>

app/views/type_foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type_food.name %>
</p>

<%= link_to 'Edit', edit_type_food_path(@type_food) %> |
<%= link_to 'Back', type_foods_path %>